In [47]:
import pandas as pd
import numpy as np
from fastprogress.fastprogress import progress_bar

## Import data files

In [2]:
file1 = pd.read_csv('GDSC1_public_raw_data_24Jul22.csv')
file1

/var/folders/nn/zyrgwx2n2kz51m6jgsh64jv00000gn/T/ipykernel_85760/63041423.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  file1 = pd.read_csv('GDSC1_public_raw_data_24Jul22.csv')

,RESEARCH_PROJECT,BARCODE,SCAN_ID,DATE_CREATED,SCAN_DATE,CELL_ID,MASTER_CELL_ID,COSMIC_ID,CELL_LINE_NAME,SANGER_MODEL_ID,SEEDING_DENSITY,DRUGSET_ID,ASSAY,DURATION,POSITION,TAG,DRUG_ID,CONC,INTENSITY
0,Sanger_GDSC1,100541,1765,2010-04-18T23:00:00Z,NaN,2415,365,924238,K5,SIDM00056,250.0,505_a_5,a,3.0,1,B,NaN,NaN,26022
1,Sanger_GDSC1,100541,1765,2010-04-18T23:00:00Z,NaN,2415,365,924238,K5,SIDM00056,250.0,505_a_5,a,3.0,2,B,NaN,NaN,20491
2,Sanger_GDSC1,100541,1765,2010-04-18T23:00:00Z,NaN,2415,365,924238,K5,SIDM00056,250.0,505_a_5,a,3.0,3,UN-USED,NaN,NaN,181946
3,Sanger_GDSC1,100541,1765,2010-04-18T23:00:00Z,NaN,2415,365,924238,K5,SIDM00056,250.0,505_a_5,a,3.0,4,UN-USED,NaN,NaN,213387
4,Sanger_GDSC1,100541,1765,2010-04-18T23:00:00Z,NaN,2415,365,924238,K5,SIDM00056,250.0,505_a_5,a,3.0,5,UN-USED,NaN,NaN,166452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5976178,MGH_GDSC1,026_144_00287710,96581,2014-08-24T23:00:00Z,NaN,3344,737,910706,BL-41,SIDM00985,NaN,26_a_7,s,NaN,380,UN-USED,NaN,NaN,688924
5976179,MGH_GDSC1,026_144_00287710,96581,2014-08-24T23:00:00Z,NaN,3344,737,910706,BL-41,SIDM00985,NaN,26_a_7,s,NaN,381,UN-USED,NaN,NaN,674334
5976180,MGH_GDSC1,026_144_00287710,96581,2014-08-24T23:00:00Z,NaN,3344,737,910706,BL-41,SIDM00985,NaN,26_a_7,s,NaN,382,UN-USED,NaN,NaN,664066
5976181,MGH_GDSC1,026_144_00287710,96581,2014-08-24T23:00:00Z,NaN,3344,737,910706,BL-41,SIDM00985,NaN,26_a_7,s,NaN,383,B,NaN,NaN,34663
5976182,MGH_GDSC1,026_144_00287710,96581,2014-08-24T23:00:00Z,NaN,3344,737,910706,BL-41,SIDM00985,NaN,26_a_7,s,NaN,384,B,NaN,NaN,33652

In [3]:
file2 = pd.read_csv('GDSC2_public_raw_data_24Jul22.csv')
file2

,RESEARCH_PROJECT,BARCODE,SCAN_ID,DATE_CREATED,SCAN_DATE,CELL_ID,MASTER_CELL_ID,COSMIC_ID,CELL_LINE_NAME,SANGER_MODEL_ID,SEEDING_DENSITY,DRUGSET_ID,ASSAY,DURATION,POSITION,TAG,DRUG_ID,CONC,INTENSITY
0,GDSC_SA,3230,2945,2015-02-13T00:00:00Z,2015-02-17T00:00:00Z,4712,198,753608,PC-14,SIDM00237,250,159,Glo,4,1,UN-USED,NaN,NaN,0
1,GDSC_SA,3230,2945,2015-02-13T00:00:00Z,2015-02-17T00:00:00Z,4712,198,753608,PC-14,SIDM00237,250,159,Glo,4,2,UN-USED,NaN,NaN,0
2,GDSC_SA,3230,2945,2015-02-13T00:00:00Z,2015-02-17T00:00:00Z,4712,198,753608,PC-14,SIDM00237,250,159,Glo,4,3,UN-USED,NaN,NaN,398
3,GDSC_SA,3230,2945,2015-02-13T00:00:00Z,2015-02-17T00:00:00Z,4712,198,753608,PC-14,SIDM00237,250,159,Glo,4,4,UN-USED,NaN,NaN,796
4,GDSC_SA,3230,2945,2015-02-13T00:00:00Z,2015-02-17T00:00:00Z,4712,198,753608,PC-14,SIDM00237,250,159,Glo,4,5,UN-USED,NaN,NaN,796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15069444,GDSC_Panc-Validation,63249,58272,2020-03-16T00:00:00Z,2020-03-20T00:00:00Z,12810,1843,1298141,Hs-766T,SIDM00664,325,630,Glo,4,1532,UN-USED,NaN,NaN,8504
15069445,GDSC_Panc-Validation,63249,58272,2020-03-16T00:00:00Z,2020-03-20T00:00:00Z,12810,1843,1298141,Hs-766T,SIDM00664,325,630,Glo,4,1533,UN-USED,NaN,NaN,5255
15069446,GDSC_Panc-Validation,63249,58272,2020-03-16T00:00:00Z,2020-03-20T00:00:00Z,12810,1843,1298141,Hs-766T,SIDM00664,325,630,Glo,4,1534,UN-USED,NaN,NaN,1051
15069447,GDSC_Panc-Validation,63249,58272,2020-03-16T00:00:00Z,2020-03-20T00:00:00Z,12810,1843,1298141,Hs-766T,SIDM00664,325,630,Glo,4,1535,UN-USED,NaN,NaN,191
15069448,GDSC_Panc-Validation,63249,58272,2020-03-16T00:00:00Z,2020-03-20T00:00:00Z,12810,1843,1298141,Hs-766T,SIDM00664,325,630,Glo,4,1536,UN-USED,NaN,NaN,96

In [4]:
# combine dataset 1 and dataset 2 into one big file

file_combo = pd.concat([file1, file2])
file_combo.drop_duplicates(inplace=True)
file_combo

,RESEARCH_PROJECT,BARCODE,SCAN_ID,DATE_CREATED,SCAN_DATE,CELL_ID,MASTER_CELL_ID,COSMIC_ID,CELL_LINE_NAME,SANGER_MODEL_ID,SEEDING_DENSITY,DRUGSET_ID,ASSAY,DURATION,POSITION,TAG,DRUG_ID,CONC,INTENSITY
0,Sanger_GDSC1,100541,1765,2010-04-18T23:00:00Z,NaN,2415,365,924238,K5,SIDM00056,250.0,505_a_5,a,3.0,1,B,NaN,NaN,26022
1,Sanger_GDSC1,100541,1765,2010-04-18T23:00:00Z,NaN,2415,365,924238,K5,SIDM00056,250.0,505_a_5,a,3.0,2,B,NaN,NaN,20491
2,Sanger_GDSC1,100541,1765,2010-04-18T23:00:00Z,NaN,2415,365,924238,K5,SIDM00056,250.0,505_a_5,a,3.0,3,UN-USED,NaN,NaN,181946
3,Sanger_GDSC1,100541,1765,2010-04-18T23:00:00Z,NaN,2415,365,924238,K5,SIDM00056,250.0,505_a_5,a,3.0,4,UN-USED,NaN,NaN,213387
4,Sanger_GDSC1,100541,1765,2010-04-18T23:00:00Z,NaN,2415,365,924238,K5,SIDM00056,250.0,505_a_5,a,3.0,5,UN-USED,NaN,NaN,166452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15069444,GDSC_Panc-Validation,63249,58272,2020-03-16T00:00:00Z,2020-03-20T00:00:00Z,12810,1843,1298141,Hs-766T,SIDM00664,325.0,630,Glo,4.0,1532,UN-USED,NaN,NaN,8504
15069445,GDSC_Panc-Validation,63249,58272,2020-03-16T00:00:00Z,2020-03-20T00:00:00Z,12810,1843,1298141,Hs-766T,SIDM00664,325.0,630,Glo,4.0,1533,UN-USED,NaN,NaN,5255
15069446,GDSC_Panc-Validation,63249,58272,2020-03-16T00:00:00Z,2020-03-20T00:00:00Z,12810,1843,1298141,Hs-766T,SIDM00664,325.0,630,Glo,4.0,1534,UN-USED,NaN,NaN,1051
15069447,GDSC_Panc-Validation,63249,58272,2020-03-16T00:00:00Z,2020-03-20T00:00:00Z,12810,1843,1298141,Hs-766T,SIDM00664,325.0,630,Glo,4.0,1535,UN-USED,NaN,NaN,191
15069448,GDSC_Panc-Validation,63249,58272,2020-03-16T00:00:00Z,2020-03-20T00:00:00Z,12810,1843,1298141,Hs-766T,SIDM00664,325.0,630,Glo,4.0,1536,UN-USED,NaN,NaN,96

## Data cleaning

In [28]:
# figure out which conditions have 3 or more replicates

# unique plate, cell, tag, drug, and concentrations
replicates = pd.DataFrame(file_combo[['DRUGSET_ID','CELL_ID','TAG','DRUG_ID','CONC']].value_counts(dropna=False))
replicates = replicates.reset_index()
replicates.rename(columns={0:'replicates'}, inplace=True)

# remove conc column and drop duplicates so it's essentially only counting replicates for one conc
replicates.drop(['CONC'], axis=1, inplace=True)
replicates.drop_duplicates(inplace=True)

# only keep 3 or more replicates
replicates = replicates[replicates['replicates']>2]
replicates

       DRUGSET_ID  CELL_ID        TAG  DRUG_ID  replicates
0             427     8570       DMSO   4000.0       10230
1             419     8570       DMSO   4000.0        9703
2             427     8570    UN-USED      NaN        8556
3             419     8570    UN-USED      NaN        8556
4             330     7110       DMSO   4000.0        4350
...           ...      ...        ...      ...         ...
395816        158     3431   L11-D5-S   1557.0           3
395817        158     3431   L11-D6-S   1557.0           3
395818        158     2786    L8-D2-S   1089.0           3
395819        159     2755  L116-D6-S   1840.0           3
395820        158     2786    R2-D7-S   1060.0           3

[395821 rows x 5 columns]

In [29]:
# remove samples we don't need

replicates = replicates[replicates['TAG']!='DMSO']
replicates = replicates[replicates['TAG']!='B']
replicates = replicates[replicates['TAG']!='UN-USED']
replicates = replicates[replicates['TAG']!='NC-1']
replicates

       DRUGSET_ID  CELL_ID        TAG  DRUG_ID  replicates
1584          427     8570   PC2-D1-S   1034.0         620
1585          427     8570   PC1-D1-S   1862.0         620
1586          419     8570   PC2-D1-S   1034.0         620
1587          419     8570   PC1-D1-S   1862.0         620
2660          419     8570       T1-S   2136.0         434
...           ...      ...        ...      ...         ...
395816        158     3431   L11-D5-S   1557.0           3
395817        158     3431   L11-D6-S   1557.0           3
395818        158     2786    L8-D2-S   1089.0           3
395819        159     2755  L116-D6-S   1840.0           3
395820        158     2786    R2-D7-S   1060.0           3

[304765 rows x 5 columns]

In [30]:
# samples with NC-0 control

replicates_control  = replicates[replicates['TAG']=='NC-0']
replicates_control

       DRUGSET_ID  CELL_ID   TAG  DRUG_ID  replicates
7170     712_f_17     2181  NC-0      NaN         288
7171     711_a_17     3490  NC-0      NaN         288
7172     712_f_17     2878  NC-0      NaN         288
7173     712_f_17     4712  NC-0      NaN         288
7174     711_a_17     2105  NC-0      NaN         288
...           ...      ...   ...      ...         ...
219575        271     2147  NC-0      NaN           6
219576        310     5513  NC-0      NaN           6
219577        217     3399  NC-0      NaN           6
219578    414_a_9     3206  NC-0      NaN           6
219579        217     3396  NC-0      NaN           6

[34034 rows x 5 columns]

In [31]:
# make a list for indexing the file_combo and dropping rows we don't need

rep_ind = []

for i in replicates.index:
    index = replicates.loc[i]
    rep_ind.append((index['DRUGSET_ID'], index['CELL_ID'], index['DRUG_ID'], index['TAG']))
    
len(rep_ind)

304765

In [32]:
# make a new file that just has the data in replicates (by plate, cell line, drug, and tag)

rep_file = file_combo.copy()
rep_file.set_index(['DRUGSET_ID','CELL_ID','DRUG_ID','TAG'], inplace=True)
rep_file = rep_file.loc[rep_ind]
rep_file

                                     RESEARCH_PROJECT BARCODE  SCAN_ID  \
DRUGSET_ID CELL_ID DRUG_ID TAG
427        8570    1034.0  PC2-D1-S        GDSC_005-A   29543    28395
                           PC2-D1-S        GDSC_005-A   29543    28395
                           PC2-D1-S        GDSC_005-A   29543    28395
                           PC2-D1-S        GDSC_005-A   29543    28395
                           PC2-D1-S        GDSC_005-A   29543    28395
...                                               ...     ...      ...
159        2755    1840.0  L116-D6-S          GDSC_SA    7659     6874
                           L116-D6-S          GDSC_SA    8070     7298
158        2786    1060.0  R2-D7-S            GDSC_SA    6617     6107
                           R2-D7-S            GDSC_SA    6864     6246
                           R2-D7-S            GDSC_SA    7265     6588

                                              DATE_CREATED  \
DRUGSET_ID CELL_ID DRUG_ID TAG
427        8570    1034.0  PC2-D1-S   2017-05-31T23:00:00Z
                           PC2-D1-S   2017-05-31T23:00:00Z
                           PC2-D1-S   2017-05-31T23:00:00Z
                           PC2-D1-S   2017-05-31T23:00:00Z
                           PC2-D1-S   2017-05-31T23:00:00Z
...                                                    ...
159        2755    1840.0  L116-D6-S  2015-07-02T23:00:00Z
                           L116-D6-S  2015-07-15T23:00:00Z
158        2786    1060.0  R2-D7-S    2015-06-11T23:00:00Z
                           R2-D7-S    2015-06-17T23:00:00Z
                           R2-D7-S    2015-06-24T23:00:00Z

                                                 SCAN_DATE  MASTER_CELL_ID  \
DRUGSET_ID CELL_ID DRUG_ID TAG
427        8570    1034.0  PC2-D1-S   2017-06-04T23:00:00Z             198
                           PC2-D1-S   2017-06-04T23:00:00Z             198
                           PC2-D1-S   2017-06-04T23:00:00Z             198
                           PC2-D1-S   2017-06-04T23:00:00Z             198
                           PC2-D1-S   2017-06-04T23:00:00Z             198
...                                                    ...             ...
159        2755    1840.0  L116-D6-S  2015-07-06T23:00:00Z             637
                           L116-D6-S  2015-07-19T23:00:00Z             637
158        2786    1060.0  R2-D7-S    2015-06-15T23:00:00Z             639
                           R2-D7-S    2015-06-21T23:00:00Z             639
                           R2-D7-S    2015-06-28T23:00:00Z             639

                                      COSMIC_ID CELL_LINE_NAME  \
DRUGSET_ID CELL_ID DRUG_ID TAG
427        8570    1034.0  PC2-D1-S      753608          PC-14
                           PC2-D1-S      753608          PC-14
                           PC2-D1-S      753608          PC-14
                           PC2-D1-S      753608          PC-14
                           PC2-D1-S      753608          PC-14
...                                         ...            ...
159        2755    1840.0  L116-D6-S     907044           HC-1
                           L116-D6-S     907044           HC-1
158        2786    1060.0  R2-D7-S      1290908         HCC-78
                           R2-D7-S      1290908         HCC-78
                           R2-D7-S      1290908         HCC-78

                                     SANGER_MODEL_ID  SEEDING_DENSITY ASSAY  \
DRUGSET_ID CELL_ID DRUG_ID TAG
427        8570    1034.0  PC2-D1-S        SIDM00237            250.0   Glo
                           PC2-D1-S        SIDM00237            250.0   Glo
                           PC2-D1-S        SIDM00237            250.0   Glo
                           PC2-D1-S        SIDM00237            250.0   Glo
                           PC2-D1-S        SIDM00237            250.0   Glo
...                                              ...              ...   ...
159        2755    1840.0  L116-D6-S       SIDM01073            625.0   Glo
                           L116-D6-S       SIDM01073            900.0   Glo
158        2786    1060.0  R2-D7-S         SIDM01068            300.0   Glo
                           R2-D7-S         SIDM01068            300.0   Glo
                           R2-D7-S         SIDM01068            350.0   Glo

                                      DURATION  POSITION      CONC  INTENSITY
DRUGSET_ID CELL_ID DRUG_ID TAG
427        8570    1034.0  PC2-D1-S        4.0       101  2.000000       4013
                           PC2-D1-S        4.0       138  2.000000       2293
                           PC2-D1-S        4.0       173  2.000000       2484
                           PC2-D1-S        4.0       308  2.000000       2771
                           PC2-D1-S        4.0       373  2.000000       2389
...                                        ...       ...       ...        ...
159        2755    1840.0  L116-D6-S       4.0       860  0.009491      72684
                           L116-D6-S       4.0       860  0.009491      60732
158        2786    1060.0  R2-D7-S         4.0       389  0.000250      30859
                           R2-D7-S         4.0       389  0.000250      34642
                           R2-D7-S         4.0       389  0.000250      35837

[2872352 rows x 15 columns]

In [73]:
# double-check that everything has replicates

rep_df = pd.DataFrame(rep_file[['CELL_ID','DRUG_ID','TAG','CONC']].value_counts(dropna=False))
rep_df

                                      0
CELL_ID DRUG_ID TAG      CONC
2181    NaN     NC-0     NaN       3720
2878    NaN     NC-0     NaN       3594
2105    NaN     NC-0     NaN       3522
3180    NaN     NC-0     NaN       3174
8570    1034.0  PC2-D1-S 2.000000  2544
...                                 ...
2787    381.0   L16-D8-S 0.156250     3
                L16-D7-S 0.312500     3
                L16-D6-S 0.625000     3
                L16-D5-S 1.250000     3
6576    1917.0  L61-D2-S 3.162555     3

[177296 rows x 1 columns]

In [74]:
# number of curves to be generated

rep_df.reset_index(inplace=True)
rep_df = rep_df[rep_df['TAG']!='NC-0']
rep_df.drop(['CONC'], axis=1, inplace=True)
rep_df.drop_duplicates(inplace=True)
len(rep_df)

/var/folders/nn/zyrgwx2n2kz51m6jgsh64jv00000gn/T/ipykernel_85760/2016580782.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rep_df.drop(['CONC'], axis=1, inplace=True)
/var/folders/nn/zyrgwx2n2kz51m6jgsh64jv00000gn/T/ipykernel_85760/2016580782.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rep_df.drop_duplicates(inplace=True)

175558

In [35]:
rep_file.to_csv('rep_combo_file.csv')

## Data normalization

In [36]:
# make a small test file for normalization

rep_file.reset_index(inplace=True)
test = rep_file[rep_file['DRUGSET_ID']=='713_a_17']
test

,DRUGSET_ID,CELL_ID,DRUG_ID,TAG,RESEARCH_PROJECT,BARCODE,SCAN_ID,DATE_CREATED,SCAN_DATE,MASTER_CELL_ID,COSMIC_ID,CELL_LINE_NAME,SANGER_MODEL_ID,SEEDING_DENSITY,ASSAY,DURATION,POSITION,CONC,INTENSITY
56008,713_a_17,3000,NaN,NC-0,Sanger_GDSC1,115429,56938,2013-02-14T00:00:00Z,NaN,1011,906790,AGS,SIDM00850,700.0,a,3.0,26,NaN,566094
56009,713_a_17,3000,NaN,NC-0,Sanger_GDSC1,115429,56938,2013-02-14T00:00:00Z,NaN,1011,906790,AGS,SIDM00850,700.0,a,3.0,47,NaN,699105
56010,713_a_17,3000,NaN,NC-0,Sanger_GDSC1,115429,56938,2013-02-14T00:00:00Z,NaN,1011,906790,AGS,SIDM00850,700.0,a,3.0,50,NaN,584060
56011,713_a_17,3000,NaN,NC-0,Sanger_GDSC1,115429,56938,2013-02-14T00:00:00Z,NaN,1011,906790,AGS,SIDM00850,700.0,a,3.0,71,NaN,730092
56012,713_a_17,3000,NaN,NC-0,Sanger_GDSC1,115429,56938,2013-02-14T00:00:00Z,NaN,1011,906790,AGS,SIDM00850,700.0,a,3.0,74,NaN,684996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2867964,713_a_17,2003,1192.0,L18-D2-S,Sanger_GDSC1,115409,57001,2013-02-14T00:00:00Z,NaN,2242,906830,C32,SIDM00890,1700.0,a,3.0,129,1.2500,238818
2867965,713_a_17,2003,1192.0,L18-D2-S,Sanger_GDSC1,115413,57002,2013-02-14T00:00:00Z,NaN,2242,906830,C32,SIDM00890,1700.0,a,3.0,129,1.2500,201052
2867966,713_a_17,2003,1192.0,L18-D3-S,Sanger_GDSC1,115401,56997,2013-02-14T00:00:00Z,NaN,2242,906830,C32,SIDM00890,1700.0,a,3.0,130,0.3125,253544
2867967,713_a_17,2003,1192.0,L18-D3-S,Sanger_GDSC1,115409,57001,2013-02-14T00:00:00Z,NaN,2242,906830,C32,SIDM00890,1700.0,a,3.0,130,0.3125,258207
2867968,713_a_17,2003,1192.0,L18-D3-S,Sanger_GDSC1,115413,57002,2013-02-14T00:00:00Z,NaN,2242,906830,C32,SIDM00890,1700.0,a,3.0,130,0.3125,221751

In [39]:
# double-check that everything has replicates

pd.DataFrame(test[['CELL_ID','DRUG_ID','TAG','CONC']].value_counts(dropna=False))

                                      0
CELL_ID DRUG_ID TAG      CONC
3257    NaN     NC-0     NaN        144
3000    NaN     NC-0     NaN        144
2878    NaN     NC-0     NaN        144
2181    NaN     NC-0     NaN        144
2833    NaN     NC-0     NaN        144
...                                 ...
        1198.0  L14-D1-S 10.000000    3
        1197.0  L6-D5-S  0.039062     3
                L6-D4-S  0.156250     3
                L6-D3-S  0.625000     3
3490    NaN     k2       NaN          3

[1243 rows x 1 columns]

In [57]:
# make a new dataframe with a normalized intensity column
# 'list_comprehension' version

test['norm_intensity'] = [(test.loc[row]['INTENSITY']) / (test[(test['CELL_ID']==test.loc[row]['CELL_ID']) & (test['DRUGSET_ID']==test.loc[row]['DRUGSET_ID']) & (test['TAG']=='NC-0')]['INTENSITY'].copy().mean()) for row in progress_bar(test.index)]

# 'for loop' version
norm = pd.DataFrame()

for plate in progress_bar(test['DRUGSET_ID'].unique()):
    df = test[test['DRUGSET_ID']==plate].copy()
    for cell in df['CELL_ID'].unique():
        df2 = df[df['CELL_ID']==cell].copy()
        df2['norm_intensity_v2'] = df2['INTENSITY'] / df2[df2['TAG']=='NC-0']['INTENSITY'].mean()
        norm = pd.concat([norm, df2])
        
norm

/var/folders/nn/zyrgwx2n2kz51m6jgsh64jv00000gn/T/ipykernel_85760/3987816675.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['norm_intensity'] = [(test.loc[row]['INTENSITY']) / (test[(test['CELL_ID']==test.loc[row]['CELL_ID']) & (test['DRUGSET_ID']==test.loc[row]['DRUGSET_ID']) & (test['TAG']=='NC-0')]['INTENSITY'].copy().mean()) for row in progress_bar(test.index)]

,DRUGSET_ID,CELL_ID,DRUG_ID,TAG,RESEARCH_PROJECT,BARCODE,SCAN_ID,DATE_CREATED,SCAN_DATE,MASTER_CELL_ID,...,CELL_LINE_NAME,SANGER_MODEL_ID,SEEDING_DENSITY,ASSAY,DURATION,POSITION,CONC,INTENSITY,norm_intensity,norm_intensity_v2
56008,713_a_17,3000,NaN,NC-0,Sanger_GDSC1,115429,56938,2013-02-14T00:00:00Z,NaN,1011,...,AGS,SIDM00850,700.0,a,3.0,26,NaN,566094,0.918598,0.918598
56009,713_a_17,3000,NaN,NC-0,Sanger_GDSC1,115429,56938,2013-02-14T00:00:00Z,NaN,1011,...,AGS,SIDM00850,700.0,a,3.0,47,NaN,699105,1.134434,1.134434
56010,713_a_17,3000,NaN,NC-0,Sanger_GDSC1,115429,56938,2013-02-14T00:00:00Z,NaN,1011,...,AGS,SIDM00850,700.0,a,3.0,50,NaN,584060,0.947751,0.947751
56011,713_a_17,3000,NaN,NC-0,Sanger_GDSC1,115429,56938,2013-02-14T00:00:00Z,NaN,1011,...,AGS,SIDM00850,700.0,a,3.0,71,NaN,730092,1.184717,1.184717
56012,713_a_17,3000,NaN,NC-0,Sanger_GDSC1,115429,56938,2013-02-14T00:00:00Z,NaN,1011,...,AGS,SIDM00850,700.0,a,3.0,74,NaN,684996,1.111540,1.111540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2862186,713_a_17,3201,NaN,k1,Sanger_GDSC1,115381,56991,2013-02-14T00:00:00Z,NaN,2112,...,MKN28,SIDM00260,800.0,a,3.0,374,NaN,159563,0.290901,0.290901
2862187,713_a_17,3201,NaN,k1,Sanger_GDSC1,115385,56992,2013-02-14T00:00:00Z,NaN,2112,...,MKN28,SIDM00260,800.0,a,3.0,374,NaN,144198,0.262889,0.262889
2862188,713_a_17,3201,NaN,k2,Sanger_GDSC1,115377,56990,2013-02-14T00:00:00Z,NaN,2112,...,MKN28,SIDM00260,800.0,a,3.0,375,NaN,104772,0.191011,0.191011
2862189,713_a_17,3201,NaN,k2,Sanger_GDSC1,115381,56991,2013-02-14T00:00:00Z,NaN,2112,...,MKN28,SIDM00260,800.0,a,3.0,375,NaN,119562,0.217975,0.217975
2862190,713_a_17,3201,NaN,k2,Sanger_GDSC1,115385,56992,2013-02-14T00:00:00Z,NaN,2112,...,MKN28,SIDM00260,800.0,a,3.0,375,NaN,168858,0.307847,0.307847

In [58]:
# 'for loop' version was much faster!

In [60]:
test.to_csv('test_norm.csv',index=False)

In [63]:
# try on full data

data_norm = pd.DataFrame()

for plate in progress_bar(rep_file['DRUGSET_ID'].unique()):
    df = rep_file[rep_file['DRUGSET_ID']==plate].copy()
    for cell in df['CELL_ID'].unique():
        df2 = df[df['CELL_ID']==cell].copy()
        df2['norm_intensity'] = df2['INTENSITY'] / df2[df2['TAG']=='NC-0']['INTENSITY'].mean()
        data_norm = pd.concat([data_norm, df2])
        
data_norm

,DRUGSET_ID,CELL_ID,DRUG_ID,TAG,RESEARCH_PROJECT,BARCODE,SCAN_ID,DATE_CREATED,SCAN_DATE,MASTER_CELL_ID,COSMIC_ID,CELL_LINE_NAME,SANGER_MODEL_ID,SEEDING_DENSITY,ASSAY,DURATION,POSITION,CONC,INTENSITY,norm_intensity
0,427,8570,1034.0,PC2-D1-S,GDSC_005-A,29543,28395,2017-05-31T23:00:00Z,2017-06-04T23:00:00Z,198,753608,PC-14,SIDM00237,250.0,Glo,4.0,101,2.0,4013,0.110151
1,427,8570,1034.0,PC2-D1-S,GDSC_005-A,29543,28395,2017-05-31T23:00:00Z,2017-06-04T23:00:00Z,198,753608,PC-14,SIDM00237,250.0,Glo,4.0,138,2.0,2293,0.062940
2,427,8570,1034.0,PC2-D1-S,GDSC_005-A,29543,28395,2017-05-31T23:00:00Z,2017-06-04T23:00:00Z,198,753608,PC-14,SIDM00237,250.0,Glo,4.0,173,2.0,2484,0.068182
3,427,8570,1034.0,PC2-D1-S,GDSC_005-A,29543,28395,2017-05-31T23:00:00Z,2017-06-04T23:00:00Z,198,753608,PC-14,SIDM00237,250.0,Glo,4.0,308,2.0,2771,0.076060
4,427,8570,1034.0,PC2-D1-S,GDSC_005-A,29543,28395,2017-05-31T23:00:00Z,2017-06-04T23:00:00Z,198,753608,PC-14,SIDM00237,250.0,Glo,4.0,373,2.0,2389,0.065575
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275525,414_a_9,3206,NaN,NC-0,MGH_GDSC1,414_194_0004680,37809,2010-11-04T00:00:00Z,NaN,628,908141,ML-2,SIDM00441,NaN,s,3.0,35,NaN,411792,0.987130
2275526,414_a_9,3206,NaN,NC-0,MGH_GDSC1,414_194_0004680,37809,2010-11-04T00:00:00Z,NaN,628,908141,ML-2,SIDM00441,NaN,s,3.0,47,NaN,414731,0.994175
2275527,414_a_9,3206,NaN,NC-0,MGH_GDSC1,414_194_0004680,37809,2010-11-04T00:00:00Z,NaN,628,908141,ML-2,SIDM00441,NaN,s,3.0,59,NaN,403578,0.967439
2275528,414_a_9,3206,NaN,NC-0,MGH_GDSC1,414_194_0004680,37809,2010-11-04T00:00:00Z,NaN,628,908141,ML-2,SIDM00441,NaN,s,3.0,71,NaN,419658,1.005986
2275529,414_a_9,3206,NaN,NC-0,MGH_GDSC1,414_194_0004680,37809,2010-11-04T00:00:00Z,NaN,628,908141,ML-2,SIDM00441,NaN,s,3.0,83,NaN,423936,1.016241

In [70]:
# take out the controls since we don't need them anymore for making curves

data_norm = data_norm[data_norm['TAG']!='NC-0']
data_norm

,DRUGSET_ID,CELL_ID,DRUG_ID,TAG,RESEARCH_PROJECT,BARCODE,SCAN_ID,DATE_CREATED,SCAN_DATE,MASTER_CELL_ID,COSMIC_ID,CELL_LINE_NAME,SANGER_MODEL_ID,SEEDING_DENSITY,ASSAY,DURATION,POSITION,CONC,INTENSITY,norm_intensity
0,427,8570,1034.0,PC2-D1-S,GDSC_005-A,29543,28395,2017-05-31T23:00:00Z,2017-06-04T23:00:00Z,198,753608,PC-14,SIDM00237,250.0,Glo,4.0,101,2.00000,4013,0.110151
1,427,8570,1034.0,PC2-D1-S,GDSC_005-A,29543,28395,2017-05-31T23:00:00Z,2017-06-04T23:00:00Z,198,753608,PC-14,SIDM00237,250.0,Glo,4.0,138,2.00000,2293,0.062940
2,427,8570,1034.0,PC2-D1-S,GDSC_005-A,29543,28395,2017-05-31T23:00:00Z,2017-06-04T23:00:00Z,198,753608,PC-14,SIDM00237,250.0,Glo,4.0,173,2.00000,2484,0.068182
3,427,8570,1034.0,PC2-D1-S,GDSC_005-A,29543,28395,2017-05-31T23:00:00Z,2017-06-04T23:00:00Z,198,753608,PC-14,SIDM00237,250.0,Glo,4.0,308,2.00000,2771,0.076060
4,427,8570,1034.0,PC2-D1-S,GDSC_005-A,29543,28395,2017-05-31T23:00:00Z,2017-06-04T23:00:00Z,198,753608,PC-14,SIDM00237,250.0,Glo,4.0,373,2.00000,2389,0.065575
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2714736,411_a_9,2046,119.0,L6-D1-S,MGH_GDSC1,411_105_0006862,39343,2011-01-14T00:00:00Z,NaN,961,909701,RPMI-6666,SIDM00813,NaN,s,3.0,74,2.00000,167767,0.381553
2714737,411_a_9,2046,119.0,L6-D1-S,MGH_GDSC1,2011-09-29 2:29:10 PM,47744,2011-09-28T23:00:00Z,NaN,961,909701,RPMI-6666,SIDM00813,NaN,s,3.0,74,2.00000,256431,0.583202
2714771,411_a_9,2046,106.0,L5-D9-S,MGH_GDSC1,411_105_0005823,38600,2010-12-09T00:00:00Z,NaN,961,909701,RPMI-6666,SIDM00813,NaN,s,3.0,70,0.03125,838473,1.906943
2714772,411_a_9,2046,106.0,L5-D9-S,MGH_GDSC1,411_105_0006862,39343,2011-01-14T00:00:00Z,NaN,961,909701,RPMI-6666,SIDM00813,NaN,s,3.0,70,0.03125,207531,0.471989
2714773,411_a_9,2046,106.0,L5-D9-S,MGH_GDSC1,2011-09-29 2:29:10 PM,47744,2011-09-28T23:00:00Z,NaN,961,909701,RPMI-6666,SIDM00813,NaN,s,3.0,70,0.03125,275780,0.627208

In [71]:
data_norm.to_csv('gdsc1_2_norm.csv', index=False)

## Limit to only triplicates

In [82]:
# find all of the conditions with exactly 3 replicates

triplicates = pd.DataFrame(data_norm[['DRUGSET_ID','CELL_ID','DRUG_ID','TAG','CONC']].value_counts(dropna=False))
triplicates.reset_index(inplace=True)
triplicates.drop(['CONC'], axis=1, inplace=True)
triplicates.drop_duplicates(inplace=True)
triplicates = triplicates[triplicates[0]==3]
triplicates

       DRUGSET_ID  CELL_ID  DRUG_ID       TAG  0
156780        529    12250   1179.0  L11-D2-S  3
156781   714_k_17     4740   1363.0  L14-D5-S  3
156782   714_k_17     4740   1364.0  L22-D3-S  3
156783        529    12250   1190.0  L12-D4-S  3
156784   714_k_17     4740   1363.0  L14-D4-S  3
...           ...      ...      ...       ... ..
270726        460     2499   1862.0  PC1-D3-S  3
270727        460     2499   1862.0  PC1-D2-S  3
270728        460     2499   1034.0  PC2-D5-S  3
270729        460     2499   1034.0  PC2-D4-S  3
270730   714_k_17     4740      NaN        k2  3

[113951 rows x 5 columns]

In [83]:
trip_ind = []

for i in triplicates.index:
    index = triplicates.loc[i]
    trip_ind.append((index['DRUGSET_ID'], index['CELL_ID'], index['DRUG_ID'], index['TAG']))
    
len(trip_ind)

113951

In [84]:
trip_file = data_norm.copy()
trip_file.set_index(['DRUGSET_ID','CELL_ID','DRUG_ID','TAG'], inplace=True)
trip_file = trip_file.loc[trip_ind]
trip_file

                                    RESEARCH_PROJECT BARCODE  SCAN_ID  \
DRUGSET_ID CELL_ID DRUG_ID TAG
529        12250   1179.0  L11-D2-S        GDSC_Plus   58626    54438
                           L11-D2-S        GDSC_Plus   58628    54441
                           L11-D2-S        GDSC_Plus   58627    54442
714_k_17   4740    1363.0  L14-D5-S     Sanger_GDSC1  127900    82603
                           L14-D5-S     Sanger_GDSC1  127910    82635
...                                              ...     ...      ...
460        2499    1034.0  PC2-D4-S       GDSC_006-B   34360    33217
                           PC2-D4-S       GDSC_006-B   34360    33217
714_k_17   4740    NaN     k2           Sanger_GDSC1  127900    82603
                           k2           Sanger_GDSC1  127910    82635
                           k2           Sanger_GDSC1  127905    82642

                                             DATE_CREATED  \
DRUGSET_ID CELL_ID DRUG_ID TAG
529        12250   1179.0  L11-D2-S  2019-09-11T23:00:00Z
                           L11-D2-S  2019-09-11T23:00:00Z
                           L11-D2-S  2019-09-11T23:00:00Z
714_k_17   4740    1363.0  L14-D5-S  2013-11-14T00:00:00Z
                           L14-D5-S  2013-11-14T00:00:00Z
...                                                   ...
460        2499    1034.0  PC2-D4-S  2017-10-22T23:00:00Z
                           PC2-D4-S  2017-10-22T23:00:00Z
714_k_17   4740    NaN     k2        2013-11-14T00:00:00Z
                           k2        2013-11-14T00:00:00Z
                           k2        2013-11-14T00:00:00Z

                                                SCAN_DATE  MASTER_CELL_ID  \
DRUGSET_ID CELL_ID DRUG_ID TAG
529        12250   1179.0  L11-D2-S  2019-09-15T23:00:00Z             339
                           L11-D2-S  2019-09-15T23:00:00Z             339
                           L11-D2-S  2019-09-15T23:00:00Z             339
714_k_17   4740    1363.0  L14-D5-S                   NaN             953
                           L14-D5-S                   NaN             953
...                                                   ...             ...
460        2499    1034.0  PC2-D4-S  2017-10-26T23:00:00Z             297
                           PC2-D4-S  2017-10-26T23:00:00Z             297
714_k_17   4740    NaN     k2                         NaN             953
                           k2                         NaN             953
                           k2                         NaN             953

                                     COSMIC_ID CELL_LINE_NAME SANGER_MODEL_ID  \
DRUGSET_ID CELL_ID DRUG_ID TAG
529        12250   1179.0  L11-D2-S     908134       MHH-ES-1       SIDM00386
                           L11-D2-S     908134       MHH-ES-1       SIDM00386
                           L11-D2-S     908134       MHH-ES-1       SIDM00386
714_k_17   4740    1363.0  L14-D5-S     906793           A375       SIDM00795
                           L14-D5-S     906793           A375       SIDM00795
...                                        ...            ...             ...
460        2499    1034.0  PC2-D4-S     908451         NOMO-1       SIDM00580
                           PC2-D4-S     908451         NOMO-1       SIDM00580
714_k_17   4740    NaN     k2           906793           A375       SIDM00795
                           k2           906793           A375       SIDM00795
                           k2           906793           A375       SIDM00795

                                     SEEDING_DENSITY ASSAY  DURATION  \
DRUGSET_ID CELL_ID DRUG_ID TAG
529        12250   1179.0  L11-D2-S            800.0   Glo       4.0
                           L11-D2-S            800.0   Glo       4.0
                           L11-D2-S            800.0   Glo       4.0
714_k_17   4740    1363.0  L14-D5-S            275.0     a       3.0
                           L14-D5-S            275.0     a       3.0
...                                              ...   ...       ...
460        2499    1034.0  PC2-D4-S           1250.0   Glo       4.0
                           PC2-D4-S           1250.0   Glo       4.0
714_k_17   4740    NaN     k2                  275.0     a       3.0
                           k2                  275.0     a       3.0
                           k2                  275.0     a       3.0

                                     POSITION      CONC  INTENSITY  \
DRUGSET_ID CELL_ID DRUG_ID TAG
529        12250   1179.0  L11-D2-S      1355  3.162555       8217
                           L11-D2-S      1355  3.162555       9842
                           L11-D2-S      1355  3.162555       9555
714_k_17   4740    1363.0  L14-D5-S       108  0.039062     604833
                           L14-D5-S       108  0.039062     575027
...                                       ...       ...        ...
460        2499    1034.0  PC2-D4-S      1207  0.031250      24081
                           PC2-D4-S      1224  0.031250      19780
714_k_17   4740    NaN     k2             376       NaN      19345
                           k2             376       NaN      21175
                           k2             376       NaN      22525

                                     norm_intensity
DRUGSET_ID CELL_ID DRUG_ID TAG
529        12250   1179.0  L11-D2-S        0.161609
                           L11-D2-S        0.193569
                           L11-D2-S        0.187924
714_k_17   4740    1363.0  L14-D5-S        1.070733
                           L14-D5-S        1.017967
...                                             ...
460        2499    1034.0  PC2-D4-S        0.636586
                           PC2-D4-S        0.522888
714_k_17   4740    NaN     k2              0.034246
                           k2              0.037486
                           k2              0.039876

[341853 rows x 16 columns]

In [88]:
trip_file.reset_index(inplace=True)
#trip_file.to_csv('triplicate_gdsc_norm.csv', index=False)

In [103]:
new_df = pd.DataFrame(columns=['DRUGSET_ID','CELL_ID','DRUG_ID','DATE_CREATED','counts'])

for plate in trip_file['DRUGSET_ID'].unique():
    df = trip_file[trip_file['DRUGSET_ID']==plate]
    for cell in df['CELL_ID'].unique():
        df2 = df[df['CELL_ID']==cell]
        for drug in df2['DRUG_ID'].unique():
            df3 = df2[df2['DRUG_ID']==drug]
            df4 = pd.DataFrame(df3[['DRUGSET_ID','CELL_ID','DRUG_ID','DATE_CREATED','CONC']].value_counts())
            df4.reset_index(inplace=True)
            df4.rename(columns={0:'counts'}, inplace=True)
            df4.drop(['CONC'], axis=1, inplace=True)
            df4.drop_duplicates(inplace=True)
            if df4['counts'][0]>3:
                print(df4)
            new_df = pd.concat([new_df, df4])
            
new_df

   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    12250   1060.0  2019-09-11T23:00:00Z       6
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    12250   1003.0  2019-09-11T23:00:00Z       9
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    12372   1003.0  2019-09-11T23:00:00Z       9
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    12372   1060.0  2019-09-11T23:00:00Z       6
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    11834   1003.0  2019-09-11T23:00:00Z       9
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    11834   1060.0  2019-09-11T23:00:00Z       6
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    10629   1003.0  2019-09-11T23:00:00Z       9
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    10629   1060.0  2019-09-11T23:00:00Z       6
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    11835   1060.0  2019-09-11T23:00:00Z       6
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    11835   1003.0  2019-09-11T23:00:00Z       9
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    10752   1003.0  2019-06-19T23:00:00Z       9
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    10752   1060.0  2019-06-19T23:00:00Z       6
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    11890   1060.0  2019-09-11T23:00:00Z       6
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529    11890   1003.0  2019-09-11T23:00:00Z       9
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529     2916   1060.0  2019-05-12T23:00:00Z       6
   DRUGSET_ID  CELL_ID  DRUG_ID          DATE_CREATED  counts
0         529     2916   1003.0  2019-05-12T23:00:00Z       9

KeyError: 0